name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Java et Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # OpenJDK
          java-version: '17'

      - name: Construire le backend
        run: ./gradlew build

      - name: Lancer les tests backend
        run: ./gradlew test

      - name: Générer l'image Docker du backend
        run: docker build -t my-backend ./backend

  frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer les dépendances
        run: npm install

      - name: Lancer les tests frontend
        run: npm test

      - name: Construire le frontend
        run: npm run build
