name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Vérifier le répertoire de travail
        run: |
          pwd
          ls -R

      - name: Installer Java et Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Construire le backend
        run: ./gradlew build

      - name: Lancer les tests backend
        run: ./gradlew test

      - name: Copier le Dockerfile à la racine
        run: cp $GITHUB_WORKSPACE/backend/src/main/docker/Dockerfile.jvm $GITHUB_WORKSPACE/backend/Dockerfile
      
      - name: Générer l'image Docker du backend
        run: |
          cd $GITHUB_WORKSPACE/backend
          docker build -t my-backend .


  frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer les dépendances
        run: npm install

      - name: Construire le frontend
        run: npm run build
